#!/usr/bin/env sh
#-------------------------------------------------------------------------------
# usage:
# 	gen_javadocs path/to/file.java
#	gen_javadocs -sourcepath path/to/src
#-------------------------------------------------------------------------------

TOP=$(git rev-parse --show-toplevel 2>/dev/null)
TOP=${TOP:-$(dirname $(dirname $0))}

set -xe

${ACTION} mkdir -p ${TOP}/out/javadoc

classpath=$(echo ${TOP}/resources/*.jar|tr ' ' ':')
${ACTION} javadoc -private -cp ${classpath} -d ${TOP}/out/javadoc $*
